### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by tobby88** [jbuchbinder/rrd-merge#1]
Hi

I am just trying to merge two rrd-files of munin. When trying to merge the new one into the old one it gives me "'New' file has older last update than 'old' file" - which is correct.
But when trying to merge the old one into the new one (like it should be) I am getting an "panic: runtime error: index out of range" error.
You can find the full log and the files I tried to merge over here: http://tobby.eu/files/share/temp/rrd-merge.zip
Any ideas why this happens?

I am using your pre-compiled 0.1.0-release (x64) with Ubuntu 14.04.3 LTS and Kernel 4.3.0.

Thanks in advance :)
Tobby

**Comment by jbuchbinder** [comment]
I have to take a bit of time to review everything -- I'm sure it's my own assumption in the code.

**Comment by jbuchbinder** [comment]
That should (theoretically) fix your issue. It's going to discard some data that doesn't fit what it's looking for; I'm assuming that the data set sizes are different, which is what's causing the panic.

The "safer" behavior is to discard but not bomb out.
